apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqldb
  labels:
    io.kompose.service: mysqldb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard