name: cluster_creation_and_addons


on:
  workflow_dispatch:
    # branches: [ "main"]
jobs:
  create_cluster:
    runs-on: self-hosted
    steps:
      - name: one script to bind them all
        run: bash ./TF_apply.sh
