name: building_from_scratch


on:
  workflow_dispatch:
jobs:
  install_tf:
    runs-on: [self-hosted]
    
    steps:
      - name: Install Terraform
       
        run: |
          apt install wget
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
          sudo wget -O- https://apt.releases.hashicorp.com/gpg | \
          sudo gpg --dearmor | \
          sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          sudo gpg --no-default-keyring \
          --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg \
          --fingerprint
          echo " stage 1"
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
          https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
          sudo tee /etc/apt/sources.list.d/hashicorp.list
          echo "stage 2"
          sudo apt update
          sudo apt-get install terraform
      - name: check version   
        run: terraform --version
        


    
